### ISSUE TITLE
`semgrepignore` comments not honored by extension in python

### ISSUE THREAD

**Issue by forana** [semgrep/semgrep-vscode#159]
Anonymized python:

```python
class MyClass (
    ABadClass,  # nosemgrep: myrule
    AnotherClass,
    ADifferentClass,
): ...
```

Anonymized rule:

```yaml
  - id: myrule
    languages:
      - python
    severity: ERROR
    message: Do not use ABadClass
    pattern-regex: .*ABadClass.*
```

Via CLI, the `nosemgrep` line correctly ignores the error. Via the plugin, the error is not ignored.
